package com.ec.reverseEngineering;
// Generated Nov 7, 2020 12:27:59 PM by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * EcCategory generated by hbm2java
 */
public class EcCategory implements java.io.Serializable {

	private Long id;
	private String name;
	private String value;
	private Set ecProducts = new HashSet(0);

	public EcCategory() {
	}

	public EcCategory(String name, String value) {
		this.name = name;
		this.value = value;
	}

	public EcCategory(String name, String value, Set ecProducts) {
		this.name = name;
		this.value = value;
		this.ecProducts = ecProducts;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public Set getEcProducts() {
		return this.ecProducts;
	}

	public void setEcProducts(Set ecProducts) {
		this.ecProducts = ecProducts;
	}

}
