package com.ec.reverseEngineering;
// Generated Nov 7, 2020 12:27:59 PM by Hibernate Tools 5.3.6.Final

/**
 * EcProductProperty generated by hbm2java
 */
public class EcProductProperty implements java.io.Serializable {

	private Integer id;
	private EcProduct ecProduct;
	private String name;
	private String value;

	public EcProductProperty() {
	}

	public EcProductProperty(EcProduct ecProduct, String name, String value) {
		this.ecProduct = ecProduct;
		this.name = name;
		this.value = value;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public EcProduct getEcProduct() {
		return this.ecProduct;
	}

	public void setEcProduct(EcProduct ecProduct) {
		this.ecProduct = ecProduct;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
