package com.ec.reverseEngineering;
// Generated Nov 7, 2020 12:27:59 PM by Hibernate Tools 5.3.6.Final

/**
 * EcVendorProduct generated by hbm2java
 */
public class EcVendorProduct implements java.io.Serializable {

	private Long id;
	private EcProduct ecProduct;
	private EcVendor ecVendor;

	public EcVendorProduct() {
	}

	public EcVendorProduct(EcProduct ecProduct, EcVendor ecVendor) {
		this.ecProduct = ecProduct;
		this.ecVendor = ecVendor;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public EcProduct getEcProduct() {
		return this.ecProduct;
	}

	public void setEcProduct(EcProduct ecProduct) {
		this.ecProduct = ecProduct;
	}

	public EcVendor getEcVendor() {
		return this.ecVendor;
	}

	public void setEcVendor(EcVendor ecVendor) {
		this.ecVendor = ecVendor;
	}

}
