package com.ec.reverseEngineering;
// Generated Nov 7, 2020 12:27:59 PM by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * EcVendor generated by hbm2java
 */
public class EcVendor implements java.io.Serializable {

	private long id;
	private String name;
	private String legalName;
	private String description;
	private Set ecVendorProducts = new HashSet(0);

	public EcVendor() {
	}

	public EcVendor(long id, String name, String legalName) {
		this.id = id;
		this.name = name;
		this.legalName = legalName;
	}

	public EcVendor(long id, String name, String legalName, String description, Set ecVendorProducts) {
		this.id = id;
		this.name = name;
		this.legalName = legalName;
		this.description = description;
		this.ecVendorProducts = ecVendorProducts;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLegalName() {
		return this.legalName;
	}

	public void setLegalName(String legalName) {
		this.legalName = legalName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getEcVendorProducts() {
		return this.ecVendorProducts;
	}

	public void setEcVendorProducts(Set ecVendorProducts) {
		this.ecVendorProducts = ecVendorProducts;
	}

}
