package com.ec.model;
// Generated Nov 7, 2020 12:39:19 PM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EcCategory generated by hbm2java
 */
@Entity
@Table(name = "ec_category", catalog = "enablecommerce")
public class EcCategory implements java.io.Serializable {

	private Long id;
	private String name;
	private String value;
	private Set<EcProduct> ecProducts = new HashSet<EcProduct>(0);

	public EcCategory() {
	}

	public EcCategory(String name, String value) {
		this.name = name;
		this.value = value;
	}

	public EcCategory(String name, String value, Set<EcProduct> ecProducts) {
		this.name = name;
		this.value = value;
		this.ecProducts = ecProducts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false, length = 90)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Value", nullable = false, length = 65535)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ecCategory")
	public Set<EcProduct> getEcProducts() {
		return this.ecProducts;
	}

	public void setEcProducts(Set<EcProduct> ecProducts) {
		this.ecProducts = ecProducts;
	}

}
