package com.ec.model;
// Generated Nov 7, 2020 12:39:19 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EcProductProperty generated by hbm2java
 */
@Entity
@Table(name = "ec_product_property", catalog = "enablecommerce")
public class EcProductProperty implements java.io.Serializable {

	private Integer id;
	private EcProduct ecProduct;
	private String name;
	private String value;

	public EcProductProperty() {
	}

	public EcProductProperty(EcProduct ecProduct, String name, String value) {
		this.ecProduct = ecProduct;
		this.name = name;
		this.value = value;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProductID", nullable = false)
	public EcProduct getEcProduct() {
		return this.ecProduct;
	}

	public void setEcProduct(EcProduct ecProduct) {
		this.ecProduct = ecProduct;
	}

	@Column(name = "Name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Value", nullable = false, length = 250)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
