package com.ec.model;
// Generated Nov 7, 2020 12:39:19 PM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EcProduct generated by hbm2java
 */
@Entity
@Table(name = "ec_product", catalog = "enablecommerce")
public class EcProduct implements java.io.Serializable {

	private Long id;
	private EcCategory ecCategory;
	private String name;
	private String description;
	private Long vendorId;
	private Set<EcVendorProduct> ecVendorProducts = new HashSet<EcVendorProduct>(0);
	private Set<EcProductProperty> ecProductProperties = new HashSet<EcProductProperty>(0);

	public EcProduct() {
	}

	public EcProduct(String name) {
		this.name = name;
	}

	public EcProduct(EcCategory ecCategory, String name, String description, Long vendorId,
			Set<EcVendorProduct> ecVendorProducts, Set<EcProductProperty> ecProductProperties) {
		this.ecCategory = ecCategory;
		this.name = name;
		this.description = description;
		this.vendorId = vendorId;
		this.ecVendorProducts = ecVendorProducts;
		this.ecProductProperties = ecProductProperties;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CategoryID")
	public EcCategory getEcCategory() {
		return this.ecCategory;
	}

	public void setEcCategory(EcCategory ecCategory) {
		this.ecCategory = ecCategory;
	}

	@Column(name = "Name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Description", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "VendorId")
	public Long getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(Long vendorId) {
		this.vendorId = vendorId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ecProduct")
	public Set<EcVendorProduct> getEcVendorProducts() {
		return this.ecVendorProducts;
	}

	public void setEcVendorProducts(Set<EcVendorProduct> ecVendorProducts) {
		this.ecVendorProducts = ecVendorProducts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ecProduct")
	public Set<EcProductProperty> getEcProductProperties() {
		return this.ecProductProperties;
	}

	public void setEcProductProperties(Set<EcProductProperty> ecProductProperties) {
		this.ecProductProperties = ecProductProperties;
	}

}
