package com.ec.model;
// Generated Nov 7, 2020 12:39:19 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EcVendorProduct generated by hbm2java
 */
@Entity
@Table(name = "ec_vendor_product", catalog = "enablecommerce")
public class EcVendorProduct implements java.io.Serializable {

	private Long id;
	private EcProduct ecProduct;
	private EcVendor ecVendor;

	public EcVendorProduct() {
	}

	public EcVendorProduct(EcProduct ecProduct, EcVendor ecVendor) {
		this.ecProduct = ecProduct;
		this.ecVendor = ecVendor;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProductID", nullable = false)
	public EcProduct getEcProduct() {
		return this.ecProduct;
	}

	public void setEcProduct(EcProduct ecProduct) {
		this.ecProduct = ecProduct;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VendorId", nullable = false)
	public EcVendor getEcVendor() {
		return this.ecVendor;
	}

	public void setEcVendor(EcVendor ecVendor) {
		this.ecVendor = ecVendor;
	}

}
