package com.ec.model;
// Generated Nov 12, 2020 9:57:01 AM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EcCategory generated by hbm2java
 */
@Entity
@Table(name = "ec_category", catalog = "enablecommerce")
public class EcCategory implements java.io.Serializable {

	private long id;
	private String name;
	private String value;
	private Set ecProducts = new HashSet(0);

	public EcCategory() {
	}

	public EcCategory(long id, String name, String value) {
		this.id = id;
		this.name = name;
		this.value = value;
	}

	public EcCategory(long id, String name, String value, Set ecProducts) {
		this.id = id;
		this.name = name;
		this.value = value;
		this.ecProducts = ecProducts;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false, length = 90)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Value", nullable = false, length = 65535)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ecCategory")
	public Set getEcProducts() {
		return this.ecProducts;
	}

	public void setEcProducts(Set ecProducts) {
		this.ecProducts = ecProducts;
	}

}
