package com.ec.model;
// Generated Nov 12, 2020 9:57:01 AM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EcProduct generated by hbm2java
 */
@Entity
@Table(name = "ec_product", catalog = "enablecommerce")
public class EcProduct implements java.io.Serializable {

	private long id;
	private EcCategory ecCategory;
	private String name;
	private String description;
	private Long vendorId;
	private Set ecVendorProducts = new HashSet(0);
	private Set ecProductProperties = new HashSet(0);

	public EcProduct() {
	}

	public EcProduct(long id, String name) {
		this.id = id;
		this.name = name;
	}

	public EcProduct(long id, EcCategory ecCategory, String name, String description, Long vendorId,
			Set ecVendorProducts, Set ecProductProperties) {
		this.id = id;
		this.ecCategory = ecCategory;
		this.name = name;
		this.description = description;
		this.vendorId = vendorId;
		this.ecVendorProducts = ecVendorProducts;
		this.ecProductProperties = ecProductProperties;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CategoryID")
	public EcCategory getEcCategory() {
		return this.ecCategory;
	}

	public void setEcCategory(EcCategory ecCategory) {
		this.ecCategory = ecCategory;
	}

	@Column(name = "Name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Description", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "VendorId")
	public Long getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(Long vendorId) {
		this.vendorId = vendorId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ecProduct")
	public Set getEcVendorProducts() {
		return this.ecVendorProducts;
	}

	public void setEcVendorProducts(Set ecVendorProducts) {
		this.ecVendorProducts = ecVendorProducts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ecProduct")
	public Set getEcProductProperties() {
		return this.ecProductProperties;
	}

	public void setEcProductProperties(Set ecProductProperties) {
		this.ecProductProperties = ecProductProperties;
	}

}
