package com.ec.model;
// Generated Nov 12, 2020 9:57:01 AM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EcVendorProduct generated by hbm2java
 */
@Entity
@Table(name = "ec_vendor_product", catalog = "enablecommerce")
public class EcVendorProduct implements java.io.Serializable {

	private long id;
	private EcProduct ecProduct;
	private EcVendor ecVendor;

	public EcVendorProduct() {
	}

	public EcVendorProduct(long id, EcProduct ecProduct, EcVendor ecVendor) {
		this.id = id;
		this.ecProduct = ecProduct;
		this.ecVendor = ecVendor;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProductID", nullable = false)
	public EcProduct getEcProduct() {
		return this.ecProduct;
	}

	public void setEcProduct(EcProduct ecProduct) {
		this.ecProduct = ecProduct;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VendorId", nullable = false)
	public EcVendor getEcVendor() {
		return this.ecVendor;
	}

	public void setEcVendor(EcVendor ecVendor) {
		this.ecVendor = ecVendor;
	}

}
